fix: uints don't work well with IPLD
storacha/go-metadata pull request #2
Opened 2024-12-13 16:57 UTC by volmedo

uint fields produce issues when marshalling and unmarshalling metadata

2024-12-14 06:28 UTC, hannahhoward commented
ok so IPLD should support unsigned ints, and we know it works for the location claim

I think I know the underlying issue here -- I made the range a tuple for the metadata to save space (because metadata is supposed to be small). see https://github.com/storacha/go-metadata/blob/main/metadata.ipldsch#L16

honestly this not the first time this has bitten us -- we first put length as optional then found out IPLD doesn't support optional for tuples. I think maybe IPLD tuple represenation for schemas in the go library may be a bit buggy/underbaked. Honestly, I think the actual fix here is to change the schema (but we need to do that BEFORE production), just make it a map, and add renames to save space. it's like 4 extra bytes and you probably make it up on being able to get optional for all the times length is not present.

2024-12-16 12:13 UTC, alanshaw commented
fix here: https://github.com/storacha/go-metadata/pull/3

2024-12-16 12:19 UTC, alanshaw requested changes
I think we should merge this instead: https://github.com/storacha/go-metadata/pull/3 😉

2024-12-16 12:41 UTC, closed without merging

2024-12-16 13:02 UTC, volmedo commented
closed in favor of #3, which is the proper solution for this issue.